ListenUDP		*:11812
ListenUDP		*:11813
ListenTLS		*:2083
LogLevel		5
LogThreadId on

tls OR-client {
	CACertificateFile	/etc/radsecproxy/certs/chain/WBA_OpenRoaming_Root.pem
	CertificateFile	/etc/radsecproxy/certs/chain.pem
	CertificateKeyFile	/etc/radsecproxy/certs/key.pem
	TLSVersion TLS1_2:
}

client -RCLIENT- {
	host -RCLIENT-
	type udp
	secret -RSECRET-
}

client 0.0.0.0/0 {
	type tls
	tls OR-client
	secret radsec
	CertificateNameCheck off
}

server OR-dynamic {
	type tls
	tls OR-client
	secret radsec
	certificateNameCheck off
	dynamicLookupCommand /etc/radsecproxy/naptr-openroaming.sh
}

realm /@.+\..+$/ { # This realm block must be placed at the end if others exist.
	server OR-dynamic
	accountingServer OR-dynamic
	accountingResponse on
}
